name: Release

# 触发条件: 这里是push以”v“开头的tag触发
name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的标签（Tag）时触发，如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17' # Jetpack Compose 推荐使用 Java 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk # 若未配置签名，默认生成未签名包
